name: PR Notifications

on:
  pull_request:
    types: [opened, reopened, ready_for_review, closed]

jobs:
  notify-pr-opened:
    if: github.event.action == 'opened' || github.event.action == 'reopened' || github.event.action == 'ready_for_review'
    runs-on: ubuntu-latest

    steps:
      - name: Get PR commit message
        id: get-commit
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        run: |
          PR_COMMITS_API="${{ github.event.pull_request.commits_url }}"
          FIRST_COMMIT_MSG=$(curl -s -H "Authorization: Bearer $GITHUB_TOKEN" "$PR_COMMITS_API" | jq -r '.[0].commit.message')
          echo "msg=${FIRST_COMMIT_MSG}" >> $GITHUB_OUTPUT

      - name: Send PR info to Discord
        env:
          DISCORD_WEBHOOK: ${{ secrets.DISCORD_WEBHOOK }}
          TITLE: ${{ github.event.pull_request.title }}
          URL: ${{ github.event.pull_request.html_url }}
          AUTHOR: ${{ github.event.pull_request.user.login }}
          COMMIT_MSG: ${{ steps.get-commit.outputs.msg }}
          DEV_ROLE_ID: ${{ secrets.DEV_ROLE_ID }}
          SOURCE_BRANCH: ${{ github.event.pull_request.head.ref }}
          TARGET_BRANCH: ${{ github.event.pull_request.base.ref }}

        run: |
          TIMESTAMP=$(date -u +"%Y-%m-%d %H:%M:%S UTC")

          curl -X POST "$DISCORD_WEBHOOK" \
            -H "Content-Type: application/json" \
            -d @- <<EOF
          {
            "content": "<@&$DEV_ROLE_ID>",
            "embeds": [
              {
                "title": "📢 New SGMS Backend Pull Request: ${TITLE}",
                "url": "${URL}",
                "description": "🌿 **Branch**: \`${SOURCE_BRANCH}\` → \`${TARGET_BRANCH}\`\n📦 **Commit**: \`${COMMIT_MSG}\`\n👤 **Author**: [${AUTHOR}](https://github.com/${AUTHOR})\n🔗 **Repository**: SGMS Backend",
                "color": 3447003,
                "author": {
                  "name": "${AUTHOR}",
                  "url": "https://github.com/${AUTHOR}"
                },
                "thumbnail": {
                  "url": "https://github.com/${AUTHOR}.png"
                },
                "footer": {
                  "text": "🕒 Opened at ${TIMESTAMP}"
                }
              }
            ]
          }
          EOF

  notify-pr-merged:
    if: github.event.action == 'closed' && github.event.pull_request.merged == true
    runs-on: ubuntu-latest

    steps:
      - name: Notify Discord on PR Merged
        env:
          DISCORD_WEBHOOK: ${{ secrets.DISCORD_WEBHOOK }}
          TITLE: ${{ github.event.pull_request.title }}
          URL: ${{ github.event.pull_request.html_url }}
          AUTHOR: ${{ github.event.pull_request.user.login }}
          MERGER: ${{ github.event.pull_request.merged_by.login }}
          SOURCE_BRANCH: ${{ github.event.pull_request.head.ref }}
          TARGET_BRANCH: ${{ github.event.pull_request.base.ref }}
        run: |
          TIMESTAMP=$(date -u +"%Y-%m-%d %H:%M:%S UTC")

          curl -X POST "$DISCORD_WEBHOOK" \
            -H "Content-Type: application/json" \
            -d @- <<EOF
          {
            "embeds": [
              {
                "title": "🎉 SGMS Backend PR Merged: ${TITLE}",
                "url": "${URL}",
                "description": "🌿 **Branch**: \`${SOURCE_BRANCH}\` → \`${TARGET_BRANCH}\`\n✅ **Status**: Successfully merged\n👤 **Author**: [${AUTHOR}](https://github.com/${AUTHOR})\n🔄 **Merged by**: [${MERGER}](https://github.com/${MERGER})\n🚀 **Auto-deployment**: Starting...",
                "color": 3066993,
                "footer": {
                  "text": "🕒 Merged at ${TIMESTAMP}"
                }
              }
            ]
          }
          EOF
