name: Test SSH Connection

on:
  workflow_dispatch:
    inputs:
      test_type:
        description: 'Type of SSH test to run'
        required: true
        default: 'basic'
        type: choice
        options:
          - basic
          - detailed
          - troubleshoot

jobs:
  test-ssh:
    name: Test SSH Connection
    runs-on: ubuntu-latest
    
    steps:
      - name: Setup SSH Agent
        uses: webfactory/ssh-agent@v0.9.0
        with:
          ssh-private-key: ${{ secrets.SSH_PRIVATE_KEY }}
          
      - name: Test SSH Connection
        run: |
          echo "🔍 Testing SSH connection to server..."
          echo "Server: ${{ secrets.SSH_HOST }}"
          echo "User: ${{ secrets.SSH_USERNAME }}"
          
          # Test 1: Basic connectivity
          echo "=== Test 1: Network Connectivity ==="
          ping -c 3 ${{ secrets.SSH_HOST }} || echo "⚠️ Ping failed"
          
          # Test 2: Port accessibility
          echo "=== Test 2: SSH Port Test ==="
          timeout 10 nc -zv ${{ secrets.SSH_HOST }} 22 || echo "⚠️ SSH port not accessible"
          
          # Test 3: DNS Resolution
          echo "=== Test 3: DNS Resolution ==="
          nslookup ${{ secrets.SSH_HOST }}
          dig ${{ secrets.SSH_HOST }} | head -20
          
          # Test 4: SSH Connection Test
          echo "=== Test 4: SSH Connection Test ==="
          ssh -o StrictHostKeyChecking=no -o ConnectTimeout=10 -o BatchMode=yes ${{ secrets.SSH_USERNAME }}@${{ secrets.SSH_HOST }} "echo 'SSH Success'; whoami; pwd" || echo "❌ SSH connection failed"
          
      - name: Detailed Network Analysis
        if: ${{ inputs.test_type == 'detailed' || inputs.test_type == 'troubleshoot' }}
        run: |
          echo "=== Detailed Network Analysis ==="
          
          # Check if domain is behind Cloudflare
          echo "🔍 Checking Cloudflare status..."
          dig ${{ secrets.SSH_HOST }} | grep -E "(CNAME|A)" || echo "No DNS records found"
          
          # Try different SSH ports
          echo "🔍 Testing alternative SSH ports..."
          for port in 22 2222 2200 22000; do
            echo "Testing port $port..."
            timeout 5 nc -zv ${{ secrets.SSH_HOST }} $port && echo "✅ Port $port is open" || echo "❌ Port $port is closed"
          done
          
          # Check IP info
          echo "🔍 Getting IP information..."
          host ${{ secrets.SSH_HOST }} || echo "Host lookup failed"
          
      - name: Troubleshooting Suggestions
        if: ${{ inputs.test_type == 'troubleshoot' }}
        run: |
          echo "=== 🛠️ Troubleshooting Suggestions ==="
          echo "1. ✅ Check if SSH is running: sudo systemctl status ssh"
          echo "2. ✅ Verify firewall: sudo ufw status"
          echo "3. ✅ Check SSH config: sudo nano /etc/ssh/sshd_config"
          echo "4. ✅ If using Cloudflare, SSH should NOT be proxied (gray cloud)"
          echo "5. ✅ Consider using direct server IP instead of domain"
          echo "6. ✅ Check if SSH port is 22 or custom port"
          echo "7. ✅ Verify SSH key in authorized_keys"
          echo "8. ✅ Check server provider firewall settings"
